baseURL :  'https://axelvanherle.github.io/'
languageCode : 'en-us'
title :  raspberryPiSite

theme : "PaperMod"

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: GitHub
                  url: https://github.com/axelvanherle/raspberryPiSite
                - name: Suprise
                  url: https://www.youtube.com/watch?v=dQw4w9WgXcQ

params:
    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    ShowWordCount: true
    ShowRssButtonInSectionTermList: true
    UseHugoToc: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false
    homeInfoParams:
        Title: "raspberryPiSite"
        Content: >
            A website built with Hugo that allows users to submit posts in markdown format. It's designed to run on any host, making it accessible and reliable. With a clean and simple design, users can easily navigate and find what they're looking for, while the robust back-end (you, but for now my raspberry pi 3B) ensures smooth performance.
            
